# This is the utilities configuration file.
# Please make your changes here.
#
# To call variables in a utility script:
# from cosipy.utilities.config import UtilitiesConfig
# in_K = UtilitiesConfig.aws2cosipy.names["in_K"]
#
# Alternatively:
# cfg_names = UtilitiesConfig.aws2cosipy.names
# in_K = cfg_names["in_K"]

# AWS2COSIPY
[aws2cosipy.names]
PRES_var = 'ps'                                 # hPa
T2_var = 't'                                    # K
in_K = true  # input data is already in K
RH2_var = 'rh'                                  # % 
G_var = 'sw_in'                                 # W/m^2 
RRR_var = 'TotalPrecipmm'                       # mm
U2_var = 'f'                                    # m/s
LWin_var = 'lw_in'                              # W/m^2 
SNOWFALL_var = 'Snowfallm'                      # m
N_var = ''
ALBEDO_var = 'Albedo_acc'                       # 0 - 1

[aws2cosipy.coords]
WRF = false
aggregate = false
aggregation_step = 'H'
delimiter = ','

[aws2cosipy.radiation]
radiationModule = 'Wohlfahrt2016' # 'Moelg2009', 'Wohlfahrt2016', 'none'
LUT = false  # If there is already a Look-up-table for topographic shading and sky-view-factor built for this area, set to True
LUT_path = "./data/static/LUT_Rad.nc"
dtstep = 3600  # time step (s)
tcart = 26  # Station time correction in hour angle units (1 is 4 min)
timezone_lon = -16  # Longitude of station
zeni_thld = 89.0  # If you do not know the exact value for your location, set value to 89.0

[aws2cosipy.points]      # location where the glacier is modeled
point_model = false
plon = -16.69
plat = 64.397422
hgt = 1527.2

[aws2cosipy.station]     # location of the aws station
stationName = 'B13'
stationAlt =  1211.2
stationLat =  64.5679  # Latitude of station

[aws2cosipy.lapse]
lapse_T = -0.006  # Temp K per  m
lapse_RH = -0.00051  # RH % per m (0 to 1)
lapse_RRR = 0.00124 # m per m    works ok on Bruarjokull using B13 as input                     
lapse_SNOWFALL = 0.0012 # Snowfall % per m (0 to 1)    works good on Bruarjokull using B13 as input

[aws2cosipy.modis]
enable = false
folder = "data/Modis_albedo"    # directory with MODIS .nc files


# CREATE STATIC FILE
[create_static.paths]
static_folder = "./data/static/"
dem_path = "DEM/vatna21_10x10m_isn93_align_lidar_zmasl_gapfilled_epsg_3057-lat_lon.tif"
shape_path = "Shapefiles/Bruarjukull_exclus.shp"
output_file = "Bruarjokull_new_static.nc"

[create_static.coords]
tile = true
aggregate = true
aggregate_degree = 0.009
longitude_upper_left = -16.935
latitude_upper_left = 64.78
longitude_lower_right = -15.37
latitude_lower_right = 64.325

# WRF2COSIPY
[wrf2cosipy.constants]
hu = 10  # Height of WRF wind velocity
lu_class = 24 # land use class for glaciers

# LANDSVIRKJUN_DATA_PREP
[landsvirkjun_data_prep.paths]
input_path = "data/input/Bruarjokull/B16_all/"
output_path = "data/input/Bruarjokull"
output_filename = "B16_inputfile.csv"
safe_individual_csv = false                      # safes the prepared individual input files as {input_filename}_rdy_conv.csv




